### ISSUE TITLE
Fix docs link on repo homepage

### ISSUE THREAD

**Issue by GrantBirki** [GrantBirki/kemal-hmac#9]
👋 Hey again @sdogruyol (sorry to keep pestering), it looks like the main link on the homepage still points to my account instead of the `kemalcr` org for the pages link. It should point here instead: https://kemalcr.github.io/kemal-hmac/

I don't have permission to update the repo in this manner (not sure if intended or not) so I wanted to drop you a ping to have it be fixed. I'm fine either way having permissions to change something like this or not and happy to just open an issue or two for quick changes like these. Thanks! 🙇

**Comment by sdogruyol** [comment]
Hey @GrantBirki, actually I gave you the default permissions. I've updated the repo desc and link as you suggested 👍
